### ISSUE TITLE
Can't update firmware

### ISSUE THREAD

**Issue by Canada51** [FeralAI/FightboardHybrid#1]

**Comment by FeralAI** [comment]
Can you provide more details? Please include the version of your Fightboard (v1 or v2) and the text/screenshots of any error messages.

**Comment by Canada51** [comment]
![fightboard](https://user-images.githubusercontent.com/89700161/131224514-a281707d-4cf0-4e79-9b67-10a9f674f0e1.PNG)

I got the v2 and also it says to click the reset button but I do not see one. I have looked all across it, and I can not find a reset button. I think that is the cause of the issue.

**Comment by Canada51** [comment]
Could you let me know where this reset button is?

**Comment by FeralAI** [comment]
There should be a small hole on top of the v2 where you can stick a toothpick or similar to double press the reset button. I'd also like to point out for the v2 you should use this release since it will support the updated LEDs in the v2: https://github.com/thnikk/FightboardHybrid/releases/tag/v0.1.1-alpha

**Comment by Canada51** [comment]
![image](https://user-images.githubusercontent.com/89700161/131226604-f23b32a0-6e3b-4ab6-9386-5af6298b9d5b.png)

now this is showing up every time

**Comment by Canada51** [comment]
i have tried it multiple times and now it shows this any time i do it

**Comment by FeralAI** [comment]
This is due to the Powershell script needing escalated privileges in order to read the correct COM port from your system automatically. You can either allow the script to run by right-clicking it and going to Security tab and Unblock it, or you can manually run the avrdude command using the manual install instructions.

**Comment by Canada51** [comment]
![image](https://user-images.githubusercontent.com/89700161/131227202-25bf499b-dc96-4796-83a1-35b652c88ff7.png)

i tried running the avrdude.exe and now this is happening

also where is the security tab to unblock the script?

**Comment by Canada51** [comment]
i am not very experienced in powershell/command prompt things

**Comment by FeralAI** [comment]
I'm sorry you're running into these issues. The latest message is saying it's expecting a certain USB driver on your system in order to detect the microcontroller board in the Fightboard. I'd prefer to not have people install drivers they won't use, do please give me some time to look into a better install procedure.

**Comment by Canada51** [comment]
so i cant use the fightboard on my switch without buying an adapter?

**Comment by FeralAI** [comment]
If you give me a day I should be able to either 1) detail a process to get it flashed on your PC or 2) come up with a better, less fiddly way to get it updated.

**Comment by Canada51** [comment]
ok so you will respond to this tomorrow or something?

**Comment by FeralAI** [comment]
I will respond by tomorrow with a status update.

**Comment by FeralAI** [comment]
I am attaching a copy of the latest libusb0.dll file (v1.2.6), which is the missing file in your error message. Please extract the .dll file and copy it into your C:\Windows\System32 folder, then retry the firmware update procedure.

[libusb0.zip](https://github.com/FeralAI/FightboardHybrid/files/7072386/libusb0.zip)

**Comment by Canada51** [comment]
![image](https://user-images.githubusercontent.com/89700161/131252186-edda0ec1-48e5-4506-914c-ffb5baf6f423.png)
well, now this error again
I double checked that it is in the right folder as well, and it was not there before because it didn't ask me to replace a file, that's weird because it's making the same error as it did when the dll wasn't there. It seems as if the file does nothing.

**Comment by FeralAI** [comment]
You can also try dropping that file in the folder with avrdude.exe.

I'm looking into building a small updater app right now, will keep you posted.

**Comment by Canada51** [comment]
![image](https://user-images.githubusercontent.com/89700161/131253428-b8898d3a-808c-4645-aab0-105677b5d68c.png)
So I tried putting the dll into the same folder as the avrdude and it changed errors, what does this mean?

**Comment by FeralAI** [comment]
Looks like libusb0.dll also needs another file called libusb0.sys in order to work properly. I'm attaching another zip with the additional file included.

Copy to the avrdude.exe folder first and try the install again.

An updater app would probably take me a few days to work out, so hopefully we can work out the driver issue.
[libusb-1.2.6.zip](https://github.com/FeralAI/FightboardHybrid/files/7072672/libusb-1.2.6.zip)

**Comment by Canada51** [comment]
same error happening
![image](https://user-images.githubusercontent.com/89700161/131253815-fdba9959-e1a0-45d0-83a9-37ee2bed63ef.png)

**Comment by FeralAI** [comment]
What version of Windows are you running?

**Comment by Canada51** [comment]
latest version of windows 10, 21H1

**Comment by Canada51** [comment]
if you need more info, just tell me

**Comment by FeralAI** [comment]
From the last zip I posted, did you use the files from the x86 or amd64 folder? That error code indicates a possible mismatch of your Windows build (32-bit/64-bit) vs the libusb version. For Win10 64-bit use the amd64 files, and x86 for Win10 32-bit. You can check that by right-clicking the Start Menu, go to System and look at the System Type field.

**Comment by Canada51** [comment]
I have a 64-bit OS, also I tried the x86 files just to be sure and nothing changed from the first error

**Comment by FeralAI** [comment]
There are tools such as Zadig that will help get the correct drivers installed for regular Arduino boards (like in the Fightboard), but this firmware changes the way the board identifies itself to the computer/console so it show up like a controller. When it's in bootloader mode (double press reset button), it shows up as an Arduino and the drivers can be installed, but that only lasts about 10 seconds which isn't enough time for Zadig to complete the process. If you would like to do some investigation, you can look into setting up avrdude with an Arduino Leonardo.

At this point I think it's best I work on the installer application to remove some of these variables for users. I understand the frustration of this not working, but we'll get it worked out so you don't have to drop $50 on a Brook adapter.

**Comment by Canada51** [comment]
So I was just looking around in the files of the updater, and I went in the update.bat file and changed the "remotesigned" to "unrestricted" and it changed to this
![image](https://user-images.githubusercontent.com/89700161/131266884-79ef3d48-d97c-45e5-b95f-5197435cfff4.png)
I tried pressing the reset button twice and while it was in bootloader mode I tried it and it does the same thing as if I didnt press it.
This may mean nothing and you might still have to work on the application, but if this has potential for something, we might want to try some more things

**Comment by Canada51** [comment]
I'm on the edge of whether I should buy an adapter or not. Do you think I should buy one or keep waiting for the installer application?

**Comment by FeralAI** [comment]
I have time set aside tonight to work on this after I take care of a few things on another project. Will post a progress update in a few hours.

**Comment by FeralAI** [comment]
I've created a simple, self-contained console application written in C#/.NET Core 3.1. Please try the following:

1. Download the TUFUpdater.zip file here (was too big to attach here): https://drive.google.com/file/d/1o-5MtY1crV5NA6saHlqUiOAOR3uDGOer/view?usp=sharing
2. Extract the `updater` folder and navigate into it.
3. Right-click `TUFUpdater.exe` and select `Run as administrator`. A console window should appear with the message `Please connect the controller and double press the reset button quickly to enter firmware update mode`.
4. With the controller attached, double press the reset button. The updater should detect when the controller is in bootloader mode and begin the update process.

Hoping this will resolve your issue. In theory you shouldn't need .NET Core 3.1 installed, but if there's a problem running it, you can get .NET Core 3.1 desktop runtime here: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-3.1.18-windows-x64-installer

**Comment by Canada51** [comment]
![image](https://user-images.githubusercontent.com/89700161/131837508-134d6e68-a4a7-4aa7-826d-db59cd1820de.png)
Well,
What do we do now?

**Comment by FeralAI** [comment]
Must be this version of avrdude doesn't like some configuration on your machine. You can try a different version of avrdude from here: https://github.com/mariusgreuel/avrdude/releases/tag/v6.3.1.1-windows. Supposedly that version fixes a bunch of issues with the libusb0 issue: https://github.com/mariusgreuel/avrdude#support-winusb-devices-via-custom-libusb

Beyond that we're into the realm of digging into your system configuration to find incompatibilities. To aid in that, you can generate a sysinfo report to help diagnose:

1. Open a run dialog (Win+R), type `msinfo32` and press Enter.
2. Go to File -> Save to generate a `.nfo` system report file
3. Attach to this thread for analysis

**Comment by Canada51** [comment]
[information.zip](https://github.com/FeralAI/FightboardHybrid/files/7098852/information.zip)
in this folder should be the .nfo file

**Comment by Canada51** [comment]
So I downloaded the newest version of avrdude and then copied everything in the updater folder except avrdude.conf and avrdude.exe and put it into the avrdude newest version folder and I ran tufupdater.exe, then I copied everything in command prompt and pasted it here, does this mean it worked?

Please connect the controller and double press the reset button quickly to enter firmware update mode
Controller found, begin firmware update

avrdude.exe: Version 6.3.1.1-windows
             Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
             Copyright (c) 2007-2014 Joerg Wunsch

             System wide configuration file is "C:\Users\aaron\Downloads\avrdude-v6.3.1.1-windows\avrdude.conf"

             Using Port                    : COM3
             Using Programmer              : avr109
             Overriding Baud Rate          : 57600
avrdude.exe: Found device at port 'COM3'
             AVR Part                      : ATmega32U4
             Chip Erase delay              : 9000 us
             PAGEL                         : PD7
             BS2                           : PA0
             RESET disposition             : dedicated
             RETRY pulse                   : SCK
             serial program mode           : yes
             parallel program mode         : yes
             Timeout                       : 200
             StabDelay                     : 100
             CmdexeDelay                   : 25
             SyncLoops                     : 32
             ByteDelay                     : 0
             PollIndex                     : 3
             PollValue                     : 0x53
             Memory Detail                 :

                                      Block Poll               Page                       Polled
               Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
               ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
               eeprom        65    20     4    0 no       1024    4      0  9000  9000 0x00 0x00
               flash         65     6   128    0 yes     32768  128    256  4500  4500 0x00 0x00
               lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
               hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
               efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
               lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
               calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
               signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

             Programmer Type : butterfly
             Description     : Atmel AppNote AVR109 Boot Loader

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude.exe: devcode selected: 0x44
avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude.exe: Device signature = 0x1e9587 (probably m32u4)
avrdude.exe: safemode: lfuse reads as FF
avrdude.exe: safemode: hfuse reads as D0
avrdude.exe: safemode: efuse reads as CB
avrdude.exe: reading input file "$C:\Users\aaron\Downloads\avrdude-v6.3.1.1-windows\FightboardHybrid.ino.hex"
avrdude.exe: can't open input file $C:\Users\aaron\Downloads\avrdude-v6.3.1.1-windows\FightboardHybrid.ino.hex: Invalid argument
avrdude.exe: read from file '$C:\Users\aaron\Downloads\avrdude-v6.3.1.1-windows\FightboardHybrid.ino.hex' failed

avrdude.exe: safemode: lfuse reads as FF
avrdude.exe: safemode: hfuse reads as D0
avrdude.exe: safemode: efuse reads as CB
avrdude.exe: safemode: Fuses OK (E:CB, H:D0, L:FF)

avrdude.exe done.  Thank you.


C:\Users\aaron\Downloads\avrdude-v6.3.1.1-windows>

**Comment by FeralAI** [comment]
We're at least past the USB driver issues and that version of avrdude is functioning. Going forward I'll use that version for the installer package.

It does seem it can't find the `.hex` firmware file though:

```
avrdude.exe: reading input file "$C:\Users\aaron\Downloads\avrdude-v6.3.1.1-windows\FightboardHybrid.ino.hex"
avrdude.exe: can't open input file $C:\Users\aaron\Downloads\avrdude-v6.3.1.1-windows\FightboardHybrid.ino.hex: Invalid argument
avrdude.exe: read from file '$C:\Users\aaron\Downloads\avrdude-v6.3.1.1-windows\FightboardHybrid.ino.hex' failed
```

**Comment by Canada51** [comment]
![image](https://user-images.githubusercontent.com/89700161/131844922-917af3b8-a1c8-478e-87f1-83767efa39c8.png)

**Comment by FeralAI** [comment]
I'm able to reproduce the file not found issue. Give me a few minutes to debug. We're almost there...

**Comment by FeralAI** [comment]
I've updated the TUFUpdater.zip package on my Google Drive: https://drive.google.com/file/d/1o-5MtY1crV5NA6saHlqUiOAOR3uDGOer/view?usp=sharing

There was a typo in the filename for the avrdude command in the TUFUpdater.exe.

**Comment by Canada51** [comment]
So, I ran that and this is what it said, however, the fightboard is not lighting up and my switch is not detecting any input from it, but my pc is. Any ideas?

Please connect the controller and double press the reset button quickly to enter firmware update mode
Controller found, begin firmware update

avrdude.exe: Version 6.3.1.1-windows
             Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
             Copyright (c) 2007-2014 Joerg Wunsch

             System wide configuration file is "C:\Users\aaron\Downloads\TUFUpdater\updater\avrdude.conf"

             Using Port                    : COM3
             Using Programmer              : avr109
             Overriding Baud Rate          : 57600
avrdude.exe: Found device at port 'COM3'
             AVR Part                      : ATmega32U4
             Chip Erase delay              : 9000 us
             PAGEL                         : PD7
             BS2                           : PA0
             RESET disposition             : dedicated
             RETRY pulse                   : SCK
             serial program mode           : yes
             parallel program mode         : yes
             Timeout                       : 200
             StabDelay                     : 100
             CmdexeDelay                   : 25
             SyncLoops                     : 32
             ByteDelay                     : 0
             PollIndex                     : 3
             PollValue                     : 0x53
             Memory Detail                 :

                                      Block Poll               Page                       Polled
               Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
               ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
               eeprom        65    20     4    0 no       1024    4      0  9000  9000 0x00 0x00
               flash         65     6   128    0 yes     32768  128    256  4500  4500 0x00 0x00
               lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
               hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
               efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
               lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
               calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
               signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

             Programmer Type : butterfly
             Description     : Atmel AppNote AVR109 Boot Loader

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude.exe: devcode selected: 0x44
avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude.exe: Device signature = 0x1e9587 (probably m32u4)
avrdude.exe: safemode: lfuse reads as FF
avrdude.exe: safemode: hfuse reads as D0
avrdude.exe: safemode: efuse reads as CB
avrdude.exe: reading input file "C:\Users\aaron\Downloads\TUFUpdater\updater\FightboardHybrid.ino.hex"
avrdude.exe: writing flash (11332 bytes):

Writing | ################################################## | 100% 1.07s

avrdude.exe: 11332 bytes of flash written
avrdude.exe: verifying flash memory against C:\Users\aaron\Downloads\TUFUpdater\updater\FightboardHybrid.ino.hex:
avrdude.exe: load data flash data from input file C:\Users\aaron\Downloads\TUFUpdater\updater\FightboardHybrid.ino.hex:
avrdude.exe: input file C:\Users\aaron\Downloads\TUFUpdater\updater\FightboardHybrid.ino.hex contains 11332 bytes
avrdude.exe: reading on-chip flash data:

Reading | ################################################## | 100% 0.28s

avrdude.exe: verifying ...
avrdude.exe: 11332 bytes of flash verified

avrdude.exe: safemode: lfuse reads as FF
avrdude.exe: safemode: hfuse reads as D0
avrdude.exe: safemode: efuse reads as CB
avrdude.exe: safemode: Fuses OK (E:CB, H:D0, L:FF)

avrdude.exe done.  Thank you.


C:\Users\aaron\Downloads\TUFUpdater\updater>

**Comment by FeralAI** [comment]
Few things to check:

- Are you in Switch mode on the controller? Hold the back/select button while plugging to ensure Switch mode is active.
- Make sure the Switch is awake, the Fightboard can't wake it from sleep.
- For the LEDs you can hold an action button to force enable an LED mode when plugging in.

Refer to the README for LED modes.

**Comment by Canada51** [comment]
I am 99% sure it is working, because i can control my switch, everything works perfectly!

**Comment by FeralAI** [comment]
Awesome! Thank you for your patience and I'm glad we finally got it all worked out for you. I'll update the repo soon with the new installer package and let thnikk know about it.
